#Server port
server:
  port: 8080
  address: localhost 

spring:
  #MySQL
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # msgs cloud DB
    # url: jdbc:mysql://db-gqosa-kr.vpc-pub-cdb.ntruss.com:3306/MSGS
    # msgs local DB
    url: jdbc:mysql://localhost:3306/msgs_hj?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: root

  #File Upload
  servlet:
    multipart: 
      enabled: true 
      max-file-size: 5MB

  # JPA
  jpa:
    # Application 구동할 때마다, Entity로 정의된 테이블을 생성
    generate-ddl: true
    hibernate:
      ddl-auto: update
    # 실행 sql문 콘솔에서 확인
    show-sql: true
    # formatter
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true
    # using database
    database: mysql
    # mysql 상세 지정
    database-platform: org.hibernate.dialect.MySQL8Dialect

  # api key include
  profiles:
    include: api


    
