tourApi:
#  decodingKey: PxzwzL1YV7V3yrJKzg9dIokQIFvxN6XmPKo+zbskQ7TVDYVhgsBn5IIZDAkUPfncj7Hlcpw+oJCCVdSdkLhuyw==
  decodingKey: xOWMRtPKnRvf0yVjbZCmX7bZlUbhfd581Ldi10fyg4b3TjvJxpjlvjH7v6Qu+mfxcUxuOxh94w2XAhcsAbWn+g==

busApi:
  decodingKey: xOWMRtPKnRvf0yVjbZCmX7bZlUbhfd581Ldi10fyg4b3TjvJxpjlvjH7v6Qu+mfxcUxuOxh94w2XAhcsAbWn+g==

smsApi:
  naver-cloud-sms.accessKey: ZDKM0uA2kPyVqXRrQfoY
  naver-cloud-sms.secretKey: 0p5mV2xKW00p8LRbq6Xk9rT4Fs0lNd6ro3CpACLJ
  naver-cloud-sms.serviceId: ncp:sms:kr:309014113851:msgs_signup
  naver-cloud-sms.senderPhone: 01027287423

jwt:
  secret: 0c930f202456658406a5d3a7be4d5a1d2a3dbfd536410b07b519c4208215fc169dcc41a8e5a2f4e70a47150c9d4b857b6fecb7c8a78035f0a8d477c44a4e11d0

ChatBot:
  secretKey: WkJ4elBWdVJnc3ZOZnBPTUVqbUF3UG1ZUFRBTWNmSWQ=
  apiUrl: https://iio8vtfz80.apigw.ntruss.com/custom/v1/10979/56191b95bfa8f08c1497b6068768b7648c900f4ec853bc73be97976bc7ce8989

objectStorage : 
  endPoint : https://kr.object.ncloudstorage.com
  regionName : regionName
  accessKey: 6fCMolib7QBe1JKwSafq
  secretKey: miJ3BdZsKPsE3WLliwHPJbJS7qaxby6F6rDiVTJa
  bucketName: msgs-file-server