tourApi:
<<<<<<< HEAD
  decodingKey: xOWMRtPKnRvf0yVjbZCmX7bZlUbhfd581Ldi10fyg4b3TjvJxpjlvjH7v6Qu%2BmfxcUxuOxh94w2XAhcsAbWn%2Bg%3D%3D
=======
  decodingKey: xOWMRtPKnRvf0yVjbZCmX7bZlUbhfd581Ldi10fyg4b3TjvJxpjlvjH7v6Qu%2BmfxcUxuOxh94w2XAhcsAbWn%2Bg%3D%3D

smsApi:
  naver-cloud-sms.accessKey: ZDKM0uA2kPyVqXRrQfoY
  naver-cloud-sms.secretKey: 0p5mV2xKW00p8LRbq6Xk9rT4Fs0lNd6ro3CpACLJ
  naver-cloud-sms.serviceId: ncp:sms:kr:309014113851:msgs_signup
  naver-cloud-sms.senderPhone: 01027287423
>>>>>>> d918fbbf4d967f8a03bff71dd3ef26101b20ec3b
